/** Word, quote and fact of the day — the same for everyone each day. */
import { dayIndex } from "../daily";

export const WORDS: { word: string; type: string; meaning: string; example: string }[] = [
  { word: "ephemeral", type: "adjective", meaning: "lasting a very short time", example: "The rainbow was ephemeral — gone in a minute." },
  { word: "meticulous", type: "adjective", meaning: "very careful about small details", example: "Her notes were meticulous, with every date underlined." },
  { word: "resilient", type: "adjective", meaning: "able to recover quickly from problems", example: "The team was resilient and won the next match." },
  { word: "ubiquitous", type: "adjective", meaning: "found everywhere", example: "Phones are ubiquitous in the playground." },
  { word: "candid", type: "adjective", meaning: "honest and direct", example: "He gave a candid answer about the test." },
  { word: "diligent", type: "adjective", meaning: "working hard and carefully", example: "A diligent student checks their homework twice." },
  { word: "eloquent", type: "adjective", meaning: "speaking or writing well and persuasively", example: "Her eloquent speech won the debate." },
  { word: "frugal", type: "adjective", meaning: "careful not to waste money", example: "Being frugal, he saved up for the game." },
  { word: "gregarious", type: "adjective", meaning: "enjoying being with other people", example: "Gregarious kids love group projects." },
  { word: "hypothesis", type: "noun", meaning: "an idea you test with an experiment", example: "Our hypothesis was that plants grow faster with music." },
  { word: "inevitable", type: "adjective", meaning: "certain to happen", example: "With that much rain, a flood was inevitable." },
  { word: "jubilant", type: "adjective", meaning: "extremely happy, especially after a success", example: "The class was jubilant when the trip was confirmed." },
  { word: "keen", type: "adjective", meaning: "eager or very interested", example: "She's keen to join the coding club." },
  { word: "lucid", type: "adjective", meaning: "clear and easy to understand", example: "The teacher gave a lucid explanation of fractions." },
  { word: "mundane", type: "adjective", meaning: "ordinary and a bit boring", example: "Even mundane chores go faster with music." },
  { word: "novice", type: "noun", meaning: "a beginner", example: "As a chess novice, he lost quickly — but learned a lot." },
  { word: "obsolete", type: "adjective", meaning: "no longer used because something newer exists", example: "Floppy disks are obsolete." },
  { word: "persevere", type: "verb", meaning: "keep trying even when it's hard", example: "Persevere and the puzzle will click." },
  { word: "quaint", type: "adjective", meaning: "charmingly old-fashioned", example: "The village had quaint little shops." },
  { word: "reluctant", type: "adjective", meaning: "not wanting to do something", example: "He was reluctant to leave the game." },
  { word: "serene", type: "adjective", meaning: "calm and peaceful", example: "The lake was serene at sunrise." },
  { word: "tenacious", type: "adjective", meaning: "not giving up easily", example: "A tenacious goalkeeper saved every shot." },
  { word: "unanimous", type: "adjective", meaning: "agreed by everyone", example: "The vote for pizza was unanimous." },
  { word: "vivid", type: "adjective", meaning: "very bright, clear or detailed", example: "She had a vivid dream about flying." },
  { word: "whimsical", type: "adjective", meaning: "playful and a little unusual", example: "The book had whimsical drawings." },
  { word: "zealous", type: "adjective", meaning: "full of energy and enthusiasm for something", example: "A zealous fan painted their face." },
  { word: "ambiguous", type: "adjective", meaning: "could mean more than one thing", example: "The question was ambiguous, so we asked." },
  { word: "benevolent", type: "adjective", meaning: "kind and wanting to help", example: "A benevolent neighbour fixed our fence." },
  { word: "concise", type: "adjective", meaning: "short but complete", example: "Keep your summary concise — five lines." },
  { word: "dilemma", type: "noun", meaning: "a hard choice between two options", example: "Pizza or pasta? A real dilemma." },
  { word: "empathy", type: "noun", meaning: "understanding how someone else feels", example: "Empathy makes you a good friend." },
  { word: "fluctuate", type: "verb", meaning: "go up and down", example: "Temperatures fluctuate in spring." },
  { word: "gratitude", type: "noun", meaning: "the feeling of being thankful", example: "She wrote a note of gratitude to her coach." },
  { word: "hinder", type: "verb", meaning: "make something harder or slower", example: "Noise can hinder concentration." },
  { word: "innovate", type: "verb", meaning: "make something new or improve it", example: "Engineers innovate to solve problems." },
  { word: "juxtapose", type: "verb", meaning: "put two things side by side to compare them", example: "The poster juxtaposes old and new phones." },
  { word: "lethargic", type: "adjective", meaning: "tired and lacking energy", example: "I felt lethargic after the long trip." },
  { word: "nostalgia", type: "noun", meaning: "a fond feeling about the past", example: "Old cartoons fill him with nostalgia." },
  { word: "optimistic", type: "adjective", meaning: "expecting good things to happen", example: "She's optimistic about the results." },
  { word: "pragmatic", type: "adjective", meaning: "practical and realistic", example: "A pragmatic plan beats a perfect one." },
];

/** Short, well-known quotes from long ago. */
export const QUOTES: { text: string; by: string }[] = [
  { text: "Well done is better than well said.", by: "Benjamin Franklin" },
  { text: "It does not matter how slowly you go as long as you do not stop.", by: "Confucius" },
  { text: "A journey of a thousand miles begins with a single step.", by: "Lao Tzu" },
  { text: "Knowing yourself is the beginning of all wisdom.", by: "Aristotle" },
  { text: "Luck is what happens when preparation meets opportunity.", by: "Seneca" },
  { text: "The secret of getting ahead is getting started.", by: "Mark Twain" },
  { text: "Whatever you are, be a good one.", by: "Abraham Lincoln" },
  { text: "Energy and persistence conquer all things.", by: "Benjamin Franklin" },
  { text: "He who asks a question is a fool for five minutes; he who does not remains a fool forever.", by: "Chinese proverb" },
  { text: "Fall seven times, stand up eight.", by: "Japanese proverb" },
  { text: "Little by little, one travels far.", by: "Spanish proverb" },
  { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", by: "Traditional saying" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", by: "Proverb" },
  { text: "Do what you can, with what you have, where you are.", by: "Theodore Roosevelt" },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", by: "African proverb" },
  { text: "We are what we repeatedly do.", by: "Will Durant, on Aristotle" },
  { text: "Patience is bitter, but its fruit is sweet.", by: "Jean-Jacques Rousseau" },
  { text: "The only way to have a friend is to be one.", by: "Ralph Waldo Emerson" },
  { text: "Kindness is the language which the deaf can hear and the blind can see.", by: "Mark Twain" },
  { text: "An investment in knowledge pays the best interest.", by: "Benjamin Franklin" },
  { text: "Great things are done by a series of small things brought together.", by: "Vincent van Gogh" },
  { text: "Life is really simple, but we insist on making it complicated.", by: "Confucius" },
  { text: "No act of kindness, no matter how small, is ever wasted.", by: "Aesop" },
  { text: "Slow and steady wins the race.", by: "Aesop" },
  { text: "The more that you read, the more things you will know.", by: "Dr. Seuss" },
  { text: "Every artist was first an amateur.", by: "Ralph Waldo Emerson" },
  { text: "Where there is a will, there is a way.", by: "Proverb" },
  { text: "Practice makes progress.", by: "Proverb" },
  { text: "Don't count the days; make the days count.", by: "Proverb" },
];

export const FACTS: string[] = [
  "Octopuses have three hearts and blue blood.",
  "Honey never really goes off — edible honey has been found in ancient Egyptian tombs.",
  "A day on Venus is longer than a year on Venus.",
  "Bananas are berries, but strawberries aren't (botanically speaking).",
  "Your brain uses about 20% of your body's energy.",
  "There are more possible chess games than atoms in the observable universe.",
  "Sharks existed before trees did.",
  "The Eiffel Tower can grow about 15 cm taller in summer as the metal expands.",
  "Wombat poo is cube-shaped.",
  "A group of flamingos is called a 'flamboyance'.",
  "Light from the Sun takes about 8 minutes to reach Earth.",
  "Sea otters hold hands while they sleep so they don't drift apart.",
  "The first computer 'bug' was a real moth found in a computer in 1947.",
  "Butterflies taste with their feet.",
  "A bolt of lightning is about five times hotter than the surface of the Sun.",
  "Koalas sleep up to 22 hours a day.",
  "The shortest war in history lasted under an hour.",
  "Water can boil and freeze at the same time at the 'triple point'.",
  "Snails can sleep for up to three years.",
  "There's a planet where it may rain glass sideways (HD 189733b).",
  "The heart of a blue whale is about the size of a small car.",
  "Cows have best friends and get stressed when separated.",
  "The letter 'E' is the most common letter in English.",
  "Mount Everest grows a few millimetres every year.",
  "Some turtles can breathe through their bottoms.",
  "The Moon slowly moves about 3.8 cm further from Earth every year.",
  "A 'jiffy' is an actual unit of time used in physics and computing.",
  "Hot water can freeze faster than cold water in some conditions (the Mpemba effect).",
  "Penguins propose with pebbles.",
  "Earth is the only planet not named after a god.",
  "Your nose can remember around 50,000 different smells.",
  "Some of the Frisbee inventor's ashes were made into Frisbees.",
  "Pineapples take about two years to grow.",
  "A bee visits about 50–100 flowers on a single trip.",
  "The dot over a lowercase 'i' or 'j' is called a tittle.",
];

const pick = <T,>(list: T[], salt: number) => list[(dayIndex() * salt) % list.length];
export const todaysWord = () => pick(WORDS, 13);
export const todaysQuote = () => pick(QUOTES, 17);
export const todaysFact = () => pick(FACTS, 23);
