/** Small daily things: the would-you-rather question and the riddle, the same for everyone each day. */

export const WYR: [string, string][] = [
  ["Only play games with a mouse", "Only play games with a controller"],
  ["Have no homework ever again", "Have a 4-day school week"],
  ["Be able to fly", "Be able to turn invisible"],
  ["Have a pet dragon", "Have a pet robot"],
  ["Live on the Moon", "Live under the sea"],
  ["Only eat pizza forever", "Never eat pizza again"],
  ["Have super speed", "Have super strength"],
  ["Know every language", "Play every instrument"],
  ["Always be 10 minutes early", "Always be 10 minutes late"],
  ["Have unlimited Wi-Fi everywhere", "Have unlimited snacks everywhere"],
  ["Be the best at maths", "Be the best at drawing"],
  ["Explore space", "Explore the deep ocean"],
  ["Have a rewind button for your life", "Have a pause button for your life"],
  ["Talk to animals", "Read people's minds"],
  ["Never be bored", "Never be tired"],
  ["Have a slide instead of stairs", "Have a trampoline instead of a bed"],
  ["Win a gaming tournament", "Win a sports championship"],
  ["Live in a treehouse", "Live in a castle"],
  ["Only watch films", "Only watch series"],
  ["Have summer all year", "Have winter all year"],
  ["Build your own game", "Build your own website"],
  ["Have a robot that does homework", "Have a robot that cooks"],
  ["Visit the past", "Visit the future"],
  ["Be a famous YouTuber", "Be a famous athlete"],
  ["Have a photographic memory", "Be able to learn anything in an hour"],
  ["Never need sleep", "Never need to eat"],
  ["Have a secret passage in your house", "Have a secret room at school"],
  ["Ride a giant tortoise to school", "Ride a giant eagle to school"],
  ["Only use a keyboard", "Only use a touchscreen"],
  ["Be a wizard", "Be a superhero"],
  ["Have free ice cream for life", "Have free cinema tickets for life"],
  ["Have a personal theme song", "Have a personal narrator"],
  ["Shrink to ant size whenever you want", "Grow to giant size whenever you want"],
  ["Play only retro games", "Play only brand-new games"],
  ["Be able to breathe underwater", "Be able to see in the dark"],
  ["Have a day with no rules", "Have a day with no screens"],
  ["Meet your favourite game character", "Meet your favourite film character"],
  ["Have the fastest computer", "Have the fastest bike"],
  ["Be on a game show", "Be in a film"],
  ["Have teleportation", "Have time travel"],
];

export const RIDDLES: { q: string; a: string }[] = [
  { q: "What has keys but can't open locks?", a: "A keyboard (or a piano)" },
  { q: "What gets wetter the more it dries?", a: "A towel" },
  { q: "What has a head and a tail but no body?", a: "A coin" },
  { q: "What can you catch but not throw?", a: "A cold" },
  { q: "The more you take, the more you leave behind. What are they?", a: "Footsteps" },
  { q: "What has hands but can't clap?", a: "A clock" },
  { q: "What goes up but never comes down?", a: "Your age" },
  { q: "What has many teeth but can't bite?", a: "A comb" },
  { q: "What is full of holes but still holds water?", a: "A sponge" },
  { q: "What runs but never walks, and has a bed but never sleeps?", a: "A river" },
  { q: "What has one eye but can't see?", a: "A needle" },
  { q: "What word is spelled wrong in every dictionary?", a: "“Wrong”" },
  { q: "What has a neck but no head?", a: "A bottle" },
  { q: "What building has the most stories?", a: "A library" },
  { q: "I'm tall when I'm young and short when I'm old. What am I?", a: "A candle" },
  { q: "What can travel around the world while staying in a corner?", a: "A stamp" },
  { q: "What has a thumb and four fingers but isn't alive?", a: "A glove" },
  { q: "What month has 28 days?", a: "All of them" },
  { q: "What can you break without touching it?", a: "A promise" },
  { q: "What has legs but doesn't walk?", a: "A table" },
  { q: "What is always in front of you but can't be seen?", a: "The future" },
  { q: "What goes through cities and fields but never moves?", a: "A road" },
  { q: "What kind of room has no doors or windows?", a: "A mushroom" },
  { q: "What has words but never speaks?", a: "A book" },
  { q: "What can fill a room but takes up no space?", a: "Light" },
  { q: "What has a ring but no finger?", a: "A phone" },
  { q: "If you have it, you want to share it. If you share it, you don't have it. What is it?", a: "A secret" },
  { q: "What has 13 hearts but no other organs?", a: "A deck of cards" },
  { q: "What invention lets you look right through a wall?", a: "A window" },
  { q: "What do you call a bear with no teeth?", a: "A gummy bear" },
  { q: "Forward I'm heavy, backward I'm not. What am I?", a: "A ton" },
  { q: "What has a bottom at the top?", a: "Your legs" },
  { q: "What 4-letter word can be written forward, backward or upside down and still be read the same?", a: "NOON" },
  { q: "What gets bigger the more you take away?", a: "A hole" },
  { q: "Where does today come before yesterday?", a: "In the dictionary" },
  { q: "What tastes better than it smells?", a: "Your tongue" },
  { q: "What has cities but no houses, and water but no fish?", a: "A map" },
  { q: "What belongs to you but other people use it more?", a: "Your name" },
  { q: "What can run but never gets tired, has a mouth but never talks?", a: "A river" },
  { q: "What comes once in a minute, twice in a moment, but never in a thousand years?", a: "The letter M" },
];

/** Today's date in UTC (matches the server), and a stable number for picking today's item. */
export const dayKey = (d = new Date()) => d.toISOString().slice(0, 10);
export function dayIndex(d = new Date()) {
  return Math.floor(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()) / 86400_000);
}
export const todaysWyr = (d = new Date()) => WYR[dayIndex(d) % WYR.length];
export const todaysRiddle = (d = new Date()) => RIDDLES[(dayIndex(d) * 7) % RIDDLES.length];
